
const WORD_DATA = {
  textbook: {

    stage1: [
      { japanese: "猫", english: "cat" },
      { japanese: "犬", english: "dog" },
      { japanese: "鳥", english: "bird" },
      { japanese: "魚", english: "fish" },
      { japanese: "水", english: "water" },
      { japanese: "火", english: "fire" },
      { japanese: "空", english: "sky" },
      { japanese: "山", english: "mountain" },
      { japanese: "川", english: "river" },
      { japanese: "海", english: "sea" },
      { japanese: "家", english: "house" },
      { japanese: "車", english: "car" },
      { japanese: "木", english: "tree" },
      { japanese: "花", english: "flower" },
      { japanese: "道", english: "road" }
    ],

    stage2: [
      { japanese: "学校", english: "school" },
      { japanese: "先生", english: "teacher" },
      { japanese: "学生", english: "student" },
      { japanese: "友達", english: "friend" },
      { japanese: "本", english: "book" },
      { japanese: "机", english: "desk" },
      { japanese: "椅子", english: "chair" },
      { japanese: "勉強する", english: "study" },
      { japanese: "学ぶ", english: "learn" },
      { japanese: "教える", english: "teach" },
      { japanese: "質問", english: "question" },
      { japanese: "答え", english: "answer" },
      { japanese: "試験", english: "exam" },
      { japanese: "成績", english: "grade" },
      { japanese: "宿題", english: "homework" }
    ],

    stage3: [
      { japanese: "駅", english: "station" },
      { japanese: "病院", english: "hospital" },
      { japanese: "銀行", english: "bank" },
      { japanese: "店", english: "shop" },
      { japanese: "会社", english: "company" },
      { japanese: "公園", english: "park" },
      { japanese: "図書館", english: "library" },
      { japanese: "空港", english: "airport" },
      { japanese: "ホテル", english: "hotel" },
      { japanese: "町", english: "town" },
      { japanese: "市", english: "city" },
      { japanese: "国", english: "country" },
      { japanese: "建物", english: "building" },
      { japanese: "道", english: "street" },
      { japanese: "橋", english: "bridge" }
    ],

    stage4: [
      { japanese: "行く", english: "go" },
      { japanese: "来る", english: "come" },
      { japanese: "帰る", english: "return" },
      { japanese: "始める", english: "start" },
      { japanese: "終わる", english: "finish" },
      { japanese: "続ける", english: "continue" },
      { japanese: "止める", english: "stop" },
      { japanese: "作る", english: "make" },
      { japanese: "使う", english: "use" },
      { japanese: "持つ", english: "have" },
      { japanese: "取る", english: "take" },
      { japanese: "見る", english: "see" },
      { japanese: "聞く", english: "hear" },
      { japanese: "話す", english: "speak" },
      { japanese: "書く", english: "write" }
    ],

    stage5: [
      { japanese: "大きい", english: "big" },
      { japanese: "小さい", english: "small" },
      { japanese: "新しい", english: "new" },
      { japanese: "古い", english: "old" },
      { japanese: "速い", english: "fast" },
      { japanese: "遅い", english: "slow" },
      { japanese: "簡単な", english: "easy" },
      { japanese: "難しい", english: "difficult" },
      { japanese: "重要な", english: "important" },
      { japanese: "必要な", english: "necessary" },
      { japanese: "安全な", english: "safe" },
      { japanese: "危険な", english: "dangerous" },
      { japanese: "正しい", english: "correct" },
      { japanese: "間違った", english: "wrong" },
      { japanese: "便利な", english: "convenient" }
    ],

    stage6: [
      { japanese: "考える", english: "think" },
      { japanese: "知る", english: "know" },
      { japanese: "理解する", english: "understand" },
      { japanese: "覚える", english: "remember" },
      { japanese: "忘れる", english: "forget" },
      { japanese: "信じる", english: "believe" },
      { japanese: "疑う", english: "doubt" },
      { japanese: "感じる", english: "feel" },
      { japanese: "選ぶ", english: "choose" },
      { japanese: "決める", english: "decide" },
      { japanese: "望む", english: "hope" },
      { japanese: "恐れる", english: "fear" },
      { japanese: "助ける", english: "help" },
      { japanese: "守る", english: "protect" },
      { japanese: "失う", english: "lose" }
    ],

    stage7: [
      { japanese: "経験", english: "experience" },
      { japanese: "意見", english: "opinion" },
      { japanese: "理由", english: "reason" },
      { japanese: "結果", english: "result" },
      { japanese: "問題", english: "problem" },
      { japanese: "解決", english: "solution" },
      { japanese: "目標", english: "goal" },
      { japanese: "計画", english: "plan" },
      { japanese: "努力", english: "effort" },
      { japanese: "成功", english: "success" },
      { japanese: "失敗", english: "failure" },
      { japanese: "挑戦", english: "challenge" },
      { japanese: "成長", english: "growth" },
      { japanese: "変化", english: "change" },
      { japanese: "選択", english: "choice" }
    ],


    stage8: [
      { japanese: "社会", english: "society" },
      { japanese: "経済", english: "economy" },
      { japanese: "政治", english: "politics" },
      { japanese: "文化", english: "culture" },
      { japanese: "歴史", english: "history" },
      { japanese: "法律", english: "law" },
      { japanese: "教育", english: "education" },
      { japanese: "環境", english: "environment" },
      { japanese: "科学", english: "science" },
      { japanese: "技術", english: "technology" },
      { japanese: "研究", english: "research" },
      { japanese: "発展", english: "development" },
      { japanese: "影響", english: "influence" },
      { japanese: "責任", english: "responsibility" },
      { japanese: "役割", english: "role" }
    ],

    stage9: [
      { japanese: "理論", english: "theory" },
      { japanese: "仮説", english: "hypothesis" },
      { japanese: "分析", english: "analysis" },
      { japanese: "証拠", english: "evidence" },
      { japanese: "結論", english: "conclusion" },
      { japanese: "前提", english: "assumption" },
      { japanese: "視点", english: "perspective" },
      { japanese: "構造", english: "structure" },
      { japanese: "要因", english: "factor" },
      { japanese: "過程", english: "process" },
      { japanese: "傾向", english: "trend" },
      { japanese: "比較", english: "comparison" },
      { japanese: "評価", english: "evaluation" },
      { japanese: "判断", english: "judgment" },
      { japanese: "検証", english: "verification" }
    ],

    stage10: [
      { japanese: "主張", english: "claim" },
      { japanese: "批判", english: "criticism" },
      { japanese: "議論", english: "discussion" },
      { japanese: "論点", english: "issue" },
      { japanese: "根拠", english: "basis" },
      { japanese: "反論", english: "counterargument" },
      { japanese: "合意", english: "agreement" },
      { japanese: "対立", english: "conflict" },
      { japanese: "提案", english: "proposal" },
      { japanese: "戦略", english: "strategy" },
      { japanese: "方針", english: "policy" },
      { japanese: "改革", english: "reform" },
      { japanese: "制度", english: "system" },
      { japanese: "管理", english: "management" },
      { japanese: "運営", english: "operation" }
    ],

    stage11: [
      { japanese: "倫理", english: "ethics" },
      { japanese: "価値", english: "value" },
      { japanese: "原則", english: "principle" },
      { japanese: "自由", english: "freedom" },
      { japanese: "平等", english: "equality" },
      { japanese: "権利", english: "right" },
      { japanese: "義務", english: "duty" },
      { japanese: "公正", english: "fairness" },
      { japanese: "正義", english: "justice" },
      { japanese: "尊重", english: "respect" },
      { japanese: "多様性", english: "diversity" },
      { japanese: "包摂", english: "inclusion" },
      { japanese: "差別", english: "discrimination" },
      { japanese: "責務", english: "obligation" },
      { japanese: "信頼", english: "trust" }
    ],

    stage12: [
      { japanese: "資源", english: "resource" },
      { japanese: "供給", english: "supply" },
      { japanese: "需要", english: "demand" },
      { japanese: "効率", english: "efficiency" },
      { japanese: "利益", english: "profit" },
      { japanese: "損失", english: "loss" },
      { japanese: "投資", english: "investment" },
      { japanese: "市場", english: "market" },
      { japanese: "競争", english: "competition" },
      { japanese: "価格", english: "price" },
      { japanese: "労働", english: "labor" },
      { japanese: "生産", english: "production" },
      { japanese: "消費", english: "consumption" },
      { japanese: "分配", english: "distribution" },
      { japanese: "影響力", english: "impact" }

    ],

    stage13: [
      { japanese: "観点", english: "viewpoint" },
      { japanese: "枠組み", english: "framework" },
      { japanese: "概念", english: "concept" },
      { japanese: "抽象的", english: "abstract" },
      { japanese: "具体的", english: "concrete" },
      { japanese: "複雑な", english: "complex" },
      { japanese: "単純な", english: "simple" },
      { japanese: "本質", english: "essence" },
      { japanese: "全体", english: "whole" },
      { japanese: "部分", english: "part" },
      { japanese: "関連", english: "relation" },
      { japanese: "相互作用", english: "interaction" },
      { japanese: "体系", english: "systematic" },
      { japanese: "機能", english: "function" },
      { japanese: "目的", english: "purpose" }
    ],

    stage14: [
      { japanese: "方法", english: "method" },
      { japanese: "手段", english: "means" },
      { japanese: "条件", english: "condition" },
      { japanese: "制約", english: "constraint" },
      { japanese: "仮定", english: "assumption" },
      { japanese: "選択肢", english: "option" },
      { japanese: "可能性", english: "possibility" },
      { japanese: "限界", english: "limit" },
      { japanese: "予測", english: "prediction" },
      { japanese: "基準", english: "criterion" },
      { japanese: "最適", english: "optimal" },
      { japanese: "代替", english: "alternative" },
      { japanese: "適応", english: "adaptation" },
      { japanese: "改善", english: "improvement" },
      { japanese: "応用", english: "application" }
    ],

    stage15: [
     { japanese: "仮定", english: "assumption" },
      { japanese: "専門", english: "specialty" },
      { japanese: "知識", english: "knowledge" },
      { japanese: "洞察", english: "insight" },
      { japanese: "創造性", english: "creativity" },
      { japanese: "継続", english: "persistence" },
      { japanese: "論理", english: "logic" },
      { japanese: "妥当性", english: "validity" },
      { japanese: "信頼性", english: "reliability" },
      { japanese: "客観性", english: "objectivity" },
      { japanese: "再現性", english: "reproducibility" },
      { japanese: "総合", english: "synthesis" },
      { japanese: "発見", english: "discovery" },
      { japanese: "革新", english: "innovation" },
      { japanese: "貢献", english: "contribution" }
    ]

  }
};